In [ ]:
import numpy as np
import pandas as pd





In [ ]:
dataset=pd.read_csv('/content/Obesity prediction.csv')



In [ ]:
dataset

Gender        Age    Height      Weight family_history FAVC  FCVC  NCP  \
0     Female  21.000000  1.620000   64.000000            yes   no   2.0  3.0   
1     Female  21.000000  1.520000   56.000000            yes   no   3.0  3.0   
2       Male  23.000000  1.800000   77.000000            yes   no   2.0  3.0   
3       Male  27.000000  1.800000   87.000000             no   no   3.0  3.0   
4       Male  22.000000  1.780000   89.800000             no   no   2.0  1.0   
...      ...        ...       ...         ...            ...  ...   ...  ...   
2106  Female  20.976842  1.710730  131.408528            yes  yes   3.0  3.0   
2107  Female  21.982942  1.748584  133.742943            yes  yes   3.0  3.0   
2108  Female  22.524036  1.752206  133.689352            yes  yes   3.0  3.0   
2109  Female  24.361936  1.739450  133.346641            yes  yes   3.0  3.0   
2110  Female  23.664709  1.738836  133.472641            yes  yes   3.0  3.0   

           CAEC SMOKE      CH2O  SCC       FAF       TUE        CALC  \
0     Sometimes    no  2.000000   no  0.000000  1.000000          no   
1     Sometimes   yes  3.000000  yes  3.000000  0.000000   Sometimes   
2     Sometimes    no  2.000000   no  2.000000  1.000000  Frequently   
3     Sometimes    no  2.000000   no  2.000000  0.000000  Frequently   
4     Sometimes    no  2.000000   no  0.000000  0.000000   Sometimes   
...         ...   ...       ...  ...       ...       ...         ...   
2106  Sometimes    no  1.728139   no  1.676269  0.906247   Sometimes   
2107  Sometimes    no  2.005130   no  1.341390  0.599270   Sometimes   
2108  Sometimes    no  2.054193   no  1.414209  0.646288   Sometimes   
2109  Sometimes    no  2.852339   no  1.139107  0.586035   Sometimes   
2110  Sometimes    no  2.863513   no  1.026452  0.714137   Sometimes   

                     MTRANS              Obesity  
0     Public_Transportation        Normal_Weight  
1     Public_Transportation        Normal_Weight  
2     Public_Transportation        Normal_Weight  
3                   Walking   Overweight_Level_I  
4     Public_Transportation  Overweight_Level_II  
...                     ...                  ...  
2106  Public_Transportation     Obesity_Type_III  
2107  Public_Transportation     Obesity_Type_III  
2108  Public_Transportation     Obesity_Type_III  
2109  Public_Transportation     Obesity_Type_III  
2110  Public_Transportation     Obesity_Type_III  

[2111 rows x 17 columns]

In [ ]:
dataset.shape


(2111, 17)

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Gender          2111 non-null   object 
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object 
 5   FAVC            2111 non-null   object 
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object 
 9   SMOKE           2111 non-null   object 
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object 
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object 
 15  MTRANS          2111 non-null   object 
 16  Obesity         2111 non-null   object 
dtypes: float64(8), object(9)
memory u

In [ ]:
dataset.isnull().sum()

Gender            0
Age               0
Height            0
Weight            0
family_history    0
FAVC              0
FCVC              0
NCP               0
CAEC              0
SMOKE             0
CH2O              0
SCC               0
FAF               0
TUE               0
CALC              0
MTRANS            0
Obesity           0
dtype: int64

In [ ]:
# Storing the first three columns in X and the last column in y
X = dataset.iloc[:, :-1]  #  all columns except the last row
y = dataset.iloc[:, -1]   # last column

# Displaying the results
print("Features (X):")
print(X)
print("\nTarget (y):")
print(y)


Features (X):
      Gender        Age    Height      Weight family_history FAVC  FCVC  NCP  \
0     Female  21.000000  1.620000   64.000000            yes   no   2.0  3.0   
1     Female  21.000000  1.520000   56.000000            yes   no   3.0  3.0   
2       Male  23.000000  1.800000   77.000000            yes   no   2.0  3.0   
3       Male  27.000000  1.800000   87.000000             no   no   3.0  3.0   
4       Male  22.000000  1.780000   89.800000             no   no   2.0  1.0   
...      ...        ...       ...         ...            ...  ...   ...  ...   
2106  Female  20.976842  1.710730  131.408528            yes  yes   3.0  3.0   
2107  Female  21.982942  1.748584  133.742943            yes  yes   3.0  3.0   
2108  Female  22.524036  1.752206  133.689352            yes  yes   3.0  3.0   
2109  Female  24.361936  1.739450  133.346641            yes  yes   3.0  3.0   
2110  Female  23.664709  1.738836  133.472641            yes  yes   3.0  3.0   

           CAEC SMOKE    

In [ ]:
y


0             Normal_Weight
1             Normal_Weight
2             Normal_Weight
3        Overweight_Level_I
4       Overweight_Level_II
               ...         
2106       Obesity_Type_III
2107       Obesity_Type_III
2108       Obesity_Type_III
2109       Obesity_Type_III
2110       Obesity_Type_III
Name: Obesity, Length: 2111, dtype: object

In [ ]:
X.infer_objects()

Gender        Age    Height      Weight family_history FAVC  FCVC  NCP  \
0     Female  21.000000  1.620000   64.000000            yes   no   2.0  3.0   
1     Female  21.000000  1.520000   56.000000            yes   no   3.0  3.0   
2       Male  23.000000  1.800000   77.000000            yes   no   2.0  3.0   
3       Male  27.000000  1.800000   87.000000             no   no   3.0  3.0   
4       Male  22.000000  1.780000   89.800000             no   no   2.0  1.0   
...      ...        ...       ...         ...            ...  ...   ...  ...   
2106  Female  20.976842  1.710730  131.408528            yes  yes   3.0  3.0   
2107  Female  21.982942  1.748584  133.742943            yes  yes   3.0  3.0   
2108  Female  22.524036  1.752206  133.689352            yes  yes   3.0  3.0   
2109  Female  24.361936  1.739450  133.346641            yes  yes   3.0  3.0   
2110  Female  23.664709  1.738836  133.472641            yes  yes   3.0  3.0   

           CAEC SMOKE      CH2O  SCC       FAF       TUE        CALC  \
0     Sometimes    no  2.000000   no  0.000000  1.000000          no   
1     Sometimes   yes  3.000000  yes  3.000000  0.000000   Sometimes   
2     Sometimes    no  2.000000   no  2.000000  1.000000  Frequently   
3     Sometimes    no  2.000000   no  2.000000  0.000000  Frequently   
4     Sometimes    no  2.000000   no  0.000000  0.000000   Sometimes   
...         ...   ...       ...  ...       ...       ...         ...   
2106  Sometimes    no  1.728139   no  1.676269  0.906247   Sometimes   
2107  Sometimes    no  2.005130   no  1.341390  0.599270   Sometimes   
2108  Sometimes    no  2.054193   no  1.414209  0.646288   Sometimes   
2109  Sometimes    no  2.852339   no  1.139107  0.586035   Sometimes   
2110  Sometimes    no  2.863513   no  1.026452  0.714137   Sometimes   

                     MTRANS  
0     Public_Transportation  
1     Public_Transportation  
2     Public_Transportation  
3                   Walking  
4     Public_Transportation  
...                     ...  
2106  Public_Transportation  
2107  Public_Transportation  
2108  Public_Transportation  
2109  Public_Transportation  
2110  Public_Transportation  

[2111 rows x 16 columns]

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Gender          2111 non-null   object 
 1   Age             2111 non-null   float64
 2   Height          2111 non-null   float64
 3   Weight          2111 non-null   float64
 4   family_history  2111 non-null   object 
 5   FAVC            2111 non-null   object 
 6   FCVC            2111 non-null   float64
 7   NCP             2111 non-null   float64
 8   CAEC            2111 non-null   object 
 9   SMOKE           2111 non-null   object 
 10  CH2O            2111 non-null   float64
 11  SCC             2111 non-null   object 
 12  FAF             2111 non-null   float64
 13  TUE             2111 non-null   float64
 14  CALC            2111 non-null   object 
 15  MTRANS          2111 non-null   object 
dtypes: float64(8), object(8)
memory usage: 264.0+ KB


In [ ]:
# WE SHOULD HANDLY THE MISSING VALUES BUT THERE ARE NO MISSING VALUES IN THE DATASET
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance
label_encoder = LabelEncoder()

# List of categorical columns to encode
categorical_cols = ['Gender', 'family_history', 'FAVC','CAEC','SMOKE',
                    'SCC', 'CALC','MTRANS']


# Loop through each categorical column and apply label encoding
for col in categorical_cols:
      X[col] = label_encoder.fit_transform(X[col])

# Display the updated DataFrame
print("\nUpdated Features (X) after Label Encoding:")
print(X)





Updated Features (X) after Label Encoding:
      Gender        Age    Height      Weight  family_history  FAVC  FCVC  \
0          0  21.000000  1.620000   64.000000               1     0   2.0   
1          0  21.000000  1.520000   56.000000               1     0   3.0   
2          1  23.000000  1.800000   77.000000               1     0   2.0   
3          1  27.000000  1.800000   87.000000               0     0   3.0   
4          1  22.000000  1.780000   89.800000               0     0   2.0   
...      ...        ...       ...         ...             ...   ...   ...   
2106       0  20.976842  1.710730  131.408528               1     1   3.0   
2107       0  21.982942  1.748584  133.742943               1     1   3.0   
2108       0  22.524036  1.752206  133.689352               1     1   3.0   
2109       0  24.361936  1.739450  133.346641               1     1   3.0   
2110       0  23.664709  1.738836  133.472641               1     1   3.0   

      NCP  CAEC  SMOKE      CH2

In [ ]:
y=label_encoder.fit_transform(y)
# Display the updated DataFrame
print("\nUpdated Features (y) after Label Encoding:")
print(y)


Updated Features (y) after Label Encoding:
[1 1 1 ... 4 4 4]


In [ ]:
y

array([1, 1, 1, ..., 4, 4, 4])

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
x_train

Gender        Age    Height      Weight  family_history  FAVC      FCVC  \
1295       0  38.148845  1.557808   79.661693               1     1  2.000000   
1627       1  40.366238  1.722396  109.349025               1     1  2.281963   
1388       0  39.648946  1.572791   80.086524               1     1  2.071622   
1318       1  23.237302  1.761008   97.829344               1     1  2.000000   
648        0  22.547298  1.722461   51.881263               1     1  2.663421   
...      ...        ...       ...         ...             ...   ...       ...   
1033       1  19.671876  1.699474   78.000000               1     0  1.925064   
1731       1  30.554956  1.779136  120.600940               1     1  2.671238   
763        1  21.000000  1.620000   70.000000               0     1  2.000000   
835        0  29.320380  1.642506   69.906708               1     1  2.366949   
1653       1  24.417552  1.774775  117.398976               1     1  2.233720   

           NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  CALC  MTRANS  
1295  3.000000     2      0  1.274774    0  0.000000  0.000000     2       0  
1627  3.770379     2      0  1.000000    0  1.330519  0.000000     3       0  
1388  2.977909     2      0  1.468297    0  0.000000  0.000000     3       0  
1318  3.000000     2      0  2.988771    0  2.429923  1.978043     3       3  
648   3.000000     1      0  1.041110    0  0.794402  1.391948     3       3  
...        ...   ...    ...       ...  ...       ...       ...   ...     ...  
1033  2.358298     2      0  2.774043    0  0.000000  0.133566     3       3  
1731  3.000000     2      0  2.145368    0  0.882709  0.593917     2       0  
763   1.000000     3      0  3.000000    0  1.000000  0.000000     2       3  
835   3.000000     2      0  1.926577    0  1.581242  0.000000     2       0  
1653  2.993634     2      0  2.028368    0  0.863158  0.449886     2       3  

[1688 rows x 16 columns]

In [ ]:
x_test

Gender        Age    Height      Weight  family_history  FAVC      FCVC  \
1730       1  30.595632  1.910672  129.232708               1     1  2.497548   
259        0  18.000000  1.670000   91.000000               1     1  1.000000   
966        1  29.153907  1.773656   87.070234               0     1  1.595746   
1911       0  18.314593  1.745602  133.554686               1     1  3.000000   
1815       0  18.771001  1.746652  133.800129               1     1  3.000000   
...      ...        ...       ...         ...             ...   ...       ...   
223        0  22.000000  1.610000   63.000000               1     1  3.000000   
1755       1  22.758998  1.859717  121.284533               1     1  2.654076   
1827       0  26.000000  1.656504  111.993054               1     1  3.000000   
1745       1  25.542454  1.763215  115.108130               1     1  2.219650   
1638       1  32.290160  1.754956  120.098812               1     1  2.967300   

           NCP  CAEC  SMOKE      CH2O  SCC       FAF       TUE  CALC  MTRANS  
1730  3.000000     2      0  1.362583    0  1.144076  0.173232     2       3  
259   3.000000     1      0  1.000000    0  0.000000  1.000000     2       3  
966   3.618722     2      0  1.274389    0  1.504003  0.370067     3       0  
1911  3.000000     2      0  2.923792    0  1.536555  0.625350     2       3  
1815  3.000000     2      0  2.869234    0  1.465931  0.627886     2       3  
...        ...   ...    ...       ...  ...       ...       ...   ...     ...  
223   3.000000     1      0  3.000000    0  1.000000  0.000000     3       3  
1755  2.574108     2      0  1.784710    0  1.170537  0.000000     2       3  
1827  3.000000     2      0  2.893117    0  0.000000  0.019310     2       3  
1745  3.000000     2      0  2.165408    0  1.315045  0.688985     2       3  
1638  3.000000     2      0  2.530035    0  0.955317  1.339232     2       0  

[423 rows x 16 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [ ]:
x_train_scaled

array([[-1.03866151,  2.18484615, -1.55781383, ..., -1.08956072,
        -0.50435687, -1.87409809],
       [ 0.96277756,  2.53555414,  0.19456719, ..., -1.08956072,
         1.43494701, -1.87409809],
       [-1.03866151,  2.42210558, -1.39828869, ..., -1.08956072,
         1.43494701, -1.87409809],
       ...,
       [ 0.96277756, -0.52745464, -0.89565085, ..., -1.08956072,
        -0.50435687,  0.50147956],
       [-1.03866151,  0.78851581, -0.65602775, ..., -1.08956072,
        -0.50435687, -1.87409809],
       [ 0.96277756,  0.01307325,  0.7522504 , ..., -0.34638064,
        -0.50435687,  0.50147956]])

In [ ]:
x_test_scaled

array([[ 0.96277756,  0.9902126 ,  2.19915615, ..., -0.80339362,
        -0.50435687,  0.50147956],
       [-1.03866151, -1.00194155, -0.36329703, ...,  0.56236906,
        -0.50435687,  0.50147956],
       [ 0.96277756,  0.76218606,  0.74033632, ..., -0.47823603,
         1.43494701, -1.87409809],
       ...,
       [-1.03866151,  0.26335687, -0.50698998, ..., -1.05766196,
        -0.50435687,  0.50147956],
       [ 0.96277756,  0.19099034,  0.6291702 , ...,  0.04859412,
        -0.50435687,  0.50147956],
       [ 0.96277756,  1.25822305,  0.54123599, ...,  1.1227565 ,
        -0.50435687, -1.87409809]])

In [ ]:
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier


from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state = 0)
classifier.fit(x_train_scaled, y_train)



DecisionTreeClassifier(random_state=0)

In [ ]:
dt_predication=classifier.predict(x_test_scaled)
print("DecisionTreeClassifier report:")
print(classification_report(y_test,dt_predication))

DecisionTreeClassifier report:
              precision    recall  f1-score   support

           0       0.94      0.91      0.92        65
           1       0.83      0.88      0.85        57
           2       0.89      0.97      0.93        67
           3       1.00      0.94      0.97        53
           4       0.97      1.00      0.99        69
           5       0.94      0.86      0.90        57
           6       0.93      0.91      0.92        55

    accuracy                           0.93       423
   macro avg       0.93      0.92      0.93       423
weighted avg       0.93      0.93      0.93       423



In [ ]:
model=RandomForestClassifier(n_estimators=100,random_state=0)
model.fit(x_train_scaled,y_train)

RandomForestClassifier(random_state=0)

In [ ]:
# Predict on the test data
y_pred = model.predict(x_test_scaled)
print("RandomForestClassifier report:")
print(classification_report(y_test, y_pred))

RandomForestClassifier report:
              precision    recall  f1-score   support

           0       0.98      0.92      0.95        65
           1       0.80      0.96      0.87        57
           2       0.97      0.99      0.98        67
           3       1.00      1.00      1.00        53
           4       1.00      1.00      1.00        69
           5       0.94      0.84      0.89        57
           6       0.94      0.89      0.92        55

    accuracy                           0.95       423
   macro avg       0.95      0.94      0.94       423
weighted avg       0.95      0.95      0.95       423

